using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace stock_transfer.Model
{
    public class Masterfile_Items
    {
        [Key]
        public string? Item_Code { get; set; }
        public string? Barcode { get; set; }
        public string? SubCode { get; set; }
        public string? Type { get; set; }
        public int? ShortCode { get; set; }
        public string? CSCode { get; set; }
        public string? CCode { get; set; }
        public string? CDesc { get; set; }
        public string? SCode { get; set; }
        public string? SDesc { get; set; }
        public string? LongDesc { get; set; }
        public string? ShortDesc { get; set; }
        public string? otherDesc { get; set; }
        public float? AvgCost { get; set; }
        public float? Reorder { get; set; }
        public float? ReorderQty { get; set; }
        public DateTime? ExpireDate { get; set; }
        public string? Location { get; set; }
        public float? Qty { get; set; }
        public float? SellPrice_1 { get; set; }
        public float? SellPrice_2 { get; set; }
        public float? SellPrice_3 { get; set; }
        public float? SellPrice_4 { get; set; }
        public float? SellPrice_5 { get; set; }
        public float? Pack1Size { get; set; }
        public float? Pack1UM { get; set; }
        public string? Department_Code { get; set; }
        public string? Photo { get; set; }
        public float? Fast { get; set; }
        public float? Slow { get; set; }
        public string? Supplier1 { get; set; }
        public string? Supplier2 { get; set; }
        public string? Supplier3 { get; set; }
        public float? SMCost1 { get; set; }
        public float? SMCost2 { get; set; }
        public float? SMPrice1 { get; set; }
        public float? SMPrice2 { get; set; }
        public float? StandardCost { get; set; }
        public float? LastCost { get; set; }
        public string? StockControl { get; set; }
        public string? UnderCostSalesControl { get; set; }
        public float? PreviousCost { get; set; }
        public string? FreeItem { get; set; }
        public string? NonActive { get; set; }
        public float? CCost { get; set; }
        public float? PDisc_1 { get; set; }
        public float? PDisc_2 { get; set; }
        public float? PDisc_3 { get; set; }
        public float? PDisc_4 { get; set; }
        public float? PDisc_5 { get; set; }
        public float? CDisc_1 { get; set; }
        public float? CDisc_2 { get; set; }
        public float? CDisc_3 { get; set; }
        public float? CDisc_4 { get; set; }
        public float? CDisc_5 { get; set; }
        public DateTime? Fdate_1 { get; set; }
        public DateTime? Fdate_2 { get; set; }
        public DateTime? Fdate_3 { get; set; }
        public DateTime? Fdate_4 { get; set; }
        public DateTime? Fdate_5 { get; set; }
        public DateTime? Tdate_1 { get; set; }
        public DateTime? Tdate_2 { get; set; }
        public DateTime? Tdate_3 { get; set; }
        public DateTime? Tdate_4 { get; set; }
        public DateTime? Tdate_5 { get; set; }
        public DateTime? Ftime_1 { get; set; }
        public DateTime? Ftime_2 { get; set; }
        public DateTime? Ftime_3 { get; set; }
        public DateTime? Ftime_4 { get; set; }
        public DateTime? Ftime_5 { get; set; }
        public DateTime? Ttime_1 { get; set; }
        public DateTime? Ttime_2 { get; set; }
        public DateTime? Ttime_3 { get; set; }
        public DateTime? Ttime_4 { get; set; }
        public DateTime? Ttime_5 { get; set; }
        public float? OpeningQty { get; set; }
        public float? OpeningAmt { get; set; }
        public float? ReceiveQty { get; set; }
        public float? ReceiveAmt { get; set; }
        public float? ReturnQty { get; set; }
        public float? ReturnAmt { get; set; }
        public float? Transfer_InQty { get; set; }
        public float? Transfer_InAmt { get; set; }
        public float? Transfer_OutQty { get; set; }
        public float? Transfer_OutAmt { get; set; }
        public float? SalesQty { get; set; }
        public float? SalesCost { get; set; }
        public float? SalesPrice { get; set; }
        public float? AdjustmentQty { get; set; }
        public float? AdjustmentAmt { get; set; }
        public float? DisposalQty { get; set; }
        public float? DisposalAmt { get; set; }
        public float? Est_ClosingQty { get; set; }
        public float? Est_ClosingAmt { get; set; }
        public float? Act_ClosingQty { get; set; }
        public float? Act_ClosingAmt { get; set; }
        public float? Supplier1UnitCost { get; set; }
        public float? Supplier2UnitCost { get; set; }
        public float? Supplier3UnitCost { get; set; }
        public float? CustomerReturnQty { get; set; }
        public float? CustomerReturnAmt { get; set; }
        public string? PointType { get; set; }
        public float? PointPerQty { get; set; }
        public float? PointPerRM { get; set; }
        public float? LowestPrice { get; set; }
        public string? AllowPriceChange { get; set; }
        public string? AllowItemDiscount { get; set; }
        public string? AllowItemExchange { get; set; }
        public string? Remark { get; set; }
        public string? Status { get; set; }
        public DateTime ModifyDate { get; set; }
        public DateTime ModifyTime { get; set; }
        public string? p1pricebreak { get; set; }
        public string? p1promotion { get; set; }
        public string? p1pwp { get; set; }
        public string? p2pricebreak { get; set; }
        public string? p2promotion { get; set; }
        public string? p2pwp { get; set; }
        public string? p3pricebreak { get; set; }
        public string? p3promotion { get; set; }
        public string? p3pwp { get; set; }
        public string? p4pricebreak { get; set; }
        public string? p4promotion { get; set; }
        public string? p4pwp { get; set; }
        public string? p5pricebreak { get; set; }
        public string? p5promotion { get; set; }
        public string? p5pwp { get; set; }
        public float? LimitedQty { get; set; }
        public float? LimitedQtyFrom { get; set; }
        public float? LimitedQtyTo { get; set; }
        public float? LimitedQtyType { get; set; }
        public DateTime? LastCostDate { get; set; }
        public byte[]? Image { get; set; }
        public string? delInd { get; set; }
        public string? purchasetax { get; set; }
        public string? salestax { get; set; }
        public int? publish { get; set; }
        public string? category { get; set; }
        public string? allocate_epo_status { get; set; }
    }
}
